# Generated by Django 2.2.2 on 2019-12-19 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, help_text='Contact phone number', max_length=17, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customer/')),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_fees', models.CharField(blank=True, max_length=20, null=True)),
                ('yearly_fees', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_fees', models.CharField(blank=True, max_length=20, null=True)),
                ('user_description', models.TextField(blank=True, help_text='user_description and about_us', null=True)),
                ('joining_reason', models.TextField(blank=True, max_length=255, null=True)),
                ('user_type', models.IntegerField(blank=True, help_text='1 Means Regular, 2 Means Prime User', null=True)),
                ('status', models.IntegerField(blank=True, help_text='1. Request Sent,2. Request Accepted, 3. Request Rejected, 4. Invitation Sent, 5. Customer, 6. Employee', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_nominated', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_send_time', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('password', models.CharField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, help_text='Contact phone number', max_length=17, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_fees', models.CharField(blank=True, max_length=20, null=True)),
                ('yearly_fees', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_fees', models.CharField(blank=True, max_length=20, null=True)),
                ('user_description', models.TextField(blank=True, help_text='user_description and about_us', null=True)),
                ('joining_reason', models.TextField(blank=True, max_length=255, null=True)),
                ('user_type', models.IntegerField(blank=True, help_text='1 Means Regular, 2 Means Prime User', null=True)),
                ('status', models.IntegerField(blank=True, help_text='1. Request Sent,2. Request Accepted, 3. Request Rejected, 4. Invitation Sent, 5. Customer, 6. Employee', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_nominated', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_send_time', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'db_table': 'user_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'first_name', 'last_name', 'email', 'is_active'], name='auth_user_id_afe805_idx'),
        ),
    ]
