# Generated by Django 2.2.2 on 2020-01-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='user_description',
            new_name='about_us',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_description',
            new_name='about_us',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_nominated',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='joining_reason',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='monthly_fees',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='registration_fees',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='yearly_fees',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_nominated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joining_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='monthly_fees',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_fees',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yearly_fees',
        ),
    ]
