# Generated by Django 2.2.2 on 2020-11-26 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200104_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRole',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical role',
                'db_table': 'roles_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='latitude',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='longitude',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='patient_check_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='visit_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='visit_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='patient_check_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='visit_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='visit_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(blank=True, help_text='Male, Female, Other', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone_no',
            field=models.CharField(default=1, help_text='Contact phone number', max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, help_text='Male, Female, Other', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=1, help_text='Contact phone number', max_length=17),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['id', 'name'], name='roles_id_1c77ee_idx'),
        ),
        migrations.AddField(
            model_name='historicalrole',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
