# Generated by Django 2.2.2 on 2020-11-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201126_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='otp_varification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_varification',
            field=models.BooleanField(default=False),
        ),
    ]
