# Generated by Django 2.2.2 on 2021-03-26 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201127_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalEducationHistory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('degree_name', models.CharField(blank=True, max_length=120, null=True)),
                ('college_name', models.CharField(blank=True, max_length=300, null=True)),
                ('start', models.CharField(blank=True, max_length=150, null=True)),
                ('end', models.CharField(blank=True, max_length=150, null=True)),
                ('is_currenty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical education history',
                'db_table': 'education_history_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(blank=True, max_length=120, null=True)),
                ('college_name', models.CharField(blank=True, max_length=300, null=True)),
                ('start', models.CharField(blank=True, max_length=150, null=True)),
                ('end', models.CharField(blank=True, max_length=150, null=True)),
                ('is_currenty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='education_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_history',
            },
        ),
        migrations.AddIndex(
            model_name='educationhistory',
            index=models.Index(fields=['id'], name='education_h_id_680acc_idx'),
        ),
    ]
