# Generated by Django 2.2 on 2021-08-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210326_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='patient_check_time',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='visit_end_time',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='visit_start_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patient_check_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='visit_end_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='visit_start_time',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='country_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='profile_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='wristband_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wristband_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=17, null=True),
        ),
    ]
