# Generated by Django 2.2 on 2021-08-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210826_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='encoded_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='encoded_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
