# Generated by Django 2.2 on 2021-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210827_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusersession',
            name='token',
            field=models.CharField(blank=True, max_length=560, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='token',
            field=models.CharField(blank=True, max_length=560, null=True),
        ),
    ]
